canbus: Add setup script and conf file for CANBUS
zephyrproject-rtos/net-tools pull request #26
Opened 2019-03-08 14:34 UTC by jukkar

The can-setup.sh script can be used to create zcan interface
which provides a Linux vcan virtual CAN interface. This script
can be used together with Zephyr native_posix CAN driver.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

2025-08-01 15:09 UTC, henrikbrixandersen requested changes

2025-08-01 15:09 UTC, henrikbrixandersen commented on can-setup.sh
> +and then removes the canbus network interface.
The default (today) is ``zcan0``. I suggest we update the usage and defaults to use that.

2025-08-01 15:09 UTC, henrikbrixandersen commented on can-setup.sh
> +    # the IP addresses etc. for the created interface.
As CAN doesn't use IP addresses, let's change this comment to something more generic:

```suggestion
    # The idea is that the configuration file will setup
    # the communication parameters etc. for the created interface.
```

2025-08-01 15:09 UTC, henrikbrixandersen commented on can-setup.sh
> +    modprobe vcan
`vcan` is only one way of using the native_sim SocketCAN adapter in Zephyr (you can also bridge it to a physical CAN network interface). It would be nice if the vcan-specific commands (and output like "Creating $IFACE") could be moved to the `zcan.conf` file.

2025-08-04 12:42 UTC, jukkar commented
@henrikbrixandersen, I updated the script according to your comments

2025-08-04 13:03 UTC, henrikbrixandersen requested changes
Can we rename the configuration files to `zcan0.conf` and `zcan0.stop` as well? This allows easier testing with e.g. redundant SocketCAN networks (zcan0, zcan1, ...) and better reflects the expected interface name.

2025-08-04 13:03 UTC, henrikbrixandersen commented on zcan.conf
> +ip link set dev $INTERFACE up
```suggestion
ip link add dev $INTERFACE type vcan
ip link property add dev $INTERFACE altname zcan0
ip link set dev $INTERFACE up
```

2025-08-04 13:03 UTC, henrikbrixandersen commented on zscan.conf.stop
> +rmmod vcan
We should not `rmmod vcan` here as the module may have other users apart from this script.

2025-08-04 13:49 UTC, jukkar commented
> Can we rename the configuration files to `zcan0.conf` and `zcan0.stop` as well?

Sure we can if needed. Note that user can set the configuration file name like this `--config zcan1.conf` but perhaps it is clearer if the default config file and the interface name are the same.

2025-08-04 13:56 UTC, henrikbrixandersen commented
> Sure we can if needed. Note that user can set the configuration file name like this --config zcan1.conf

Understood. 

> but perhaps it is clearer if the default config file and the interface name are the same.

I think that would be preferable.

2025-08-07 10:51 UTC, henrikbrixandersen requested changes
Just two remaining changes for the default configuration scripts, otherwise looks - and works - good!

2025-08-07 10:51 UTC, henrikbrixandersen commented on zcan0.conf
> +ip link property add dev $INTERFACE altname zcan0
```suggestion
ip link add dev $INTERFACE type vcan altname zcan0
```

2025-08-07 10:51 UTC, henrikbrixandersen commented on zcan0.conf.stop
> +ip link set $INTERFACE down
```suggestion
ip link set $INTERFACE down
ip link delete $INTERFACE
```

2025-08-08 06:43 UTC, jukkar commented
@henrikbrixandersen, updated according to your comments

2025-08-08 08:37 UTC, henrikbrixandersen approved these changes

2025-08-08 08:37 UTC, henrikbrixandersen commented
Thanks @jukkar!

2025-08-11 11:56 UTC, rlubos approved these changes

2025-08-11 12:45 UTC, merged